VolunteerProject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('catalog/', include('catalog.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/urls.py
from django.urls import path

from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name='home'),
]

store/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from . import views

app_name = 'store'

urlpatterns = [
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from . import views

app_name = 'users'

urlpatterns = [
    path('singup/volunteer', views.reg_volunteer, name='reg_vol'),
    path('singup/validator', views.reg_validator, name='reg_val'),
    path('singup/organization', views.reg_organization, name='reg_org'),
    path('login', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('account/<int:id>', views.personal_account, name='account'),
    path('account/<int:id>/edit', views.EditProfile, name='edit'),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'homepage/homepage.html')

templates/homepage/homepage.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
        <h1 class="display-5 fst-italic">Ремарка от разработчиков:</h1>
        <p class="lead my-3">Медиа-файлы взяты с открытых ресурсов сети интернет,
            а компании и вакансии вымышлены и являются примером</p>
        <p class="lead mb-0"><a href="" class="text-white fw-bold">Спасибо за понимание</a></p>
    </div>
</div>
<div class="row g-5 text-white">
    <div class="col">
        <h2 class="pb-4 mb-4 border-bottom">Визитка</h2>

        <article class="blog-post">
            <h4 class="blog-post-title">Мы предоставляем:</h4>
            <p><strong>Волонтерам: </strong> Удобную площадку реализации своей деятельности, льготы</p>
            <p><strong>Организациям: </strong>Заинтерисованных волонтеров и платформу для их организации</p>
            <hr>
            <h4 class="blog-post-title">Результаты:</h4>
            <p>Мы создали удобную платформу взаимодействия государства,
                волонтерских организаций и добровольцев с целью стимулировать добровольческое движение в России.</p>
            <img src="{% static 'homepage/home_1.jpg' %}" height="100%" width="100%">
        </article>
    </div>
</div>
{% if not user.is_authenticated %}
<div class="card blockky" style="background: #C5C6C7;">
    <div class="card-body text-center">
        <a href="{% url 'users:login' %}">Войти</a>
    </div>
</div>
<div class="card blockky" style="background: #C5C6C7;">
    <div class="card-body text-center">
        <h4>Вы можете зарегистрироваться как:</h4>
        <hr>
        <h5><a href="{% url 'users:reg_vol' %}">Волонтёр</a></h5>
        <h5><a href="{% url 'users:reg_val' %}">Проверяющий</a></h5>
        <h5><a href="{% url 'users:reg_org' %}">Организация</a></h5>
    </div>
</div>
{% endif %}
{% endblock %}