VolunteerProject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('catalog/', include('catalog.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.urls import path
from . import views

app_name = 'catalog'

urlpatterns = [
    path('add', views.add_task, name='add_task'),
    path('', views.catalog, name='catalog'),
    path('task/<int:id>', views.catalog, name='task'),
]

homepage/urls.py
from django.urls import path

from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name='home'),
]

store/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from . import views

app_name = 'store'

urlpatterns = [
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from . import views

app_name = 'users'

urlpatterns = [
    path('singup/volunteer', views.reg_volunteer, name='reg_vol'),
    path('singup/validator', views.reg_validator, name='reg_val'),
    path('singup/organization', views.reg_organization, name='reg_org'),
    path('login', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('account/<int:id>', views.personal_account, name='account'),
    path('account/<int:id>/edit', views.EditProfile, name='edit'),
]

templates/includes/endscripts.html
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

templates/includes/footer.html
<footer class="my-5 pt-5 text-muted text-center text-small">
    <p class="mb-1">VolunteerProject 2023-2024</p>
</footer>

templates/includes/header.html
{% load static %}

{% url 'homepage:home' as homepage_home %}
{% url 'users:account' user.id as users_account %}
{% url 'catalog:catalog' as catalog %}

<header class="p-1 text-white" style="background: #0C0B10;">
    <div class="d-flex justify-content-center py-1">
                <img class="px-2" src="{% static 'favicon/favicon.ico' %}">
        <ul class="nav nav-pills nav-fill">
            <li><a href="{% url 'homepage:home' %}" class="nav-link px-2 text-{% if request.path == homepage_home %}white{% else %}secondary{% endif %}">Главная</a></li>
            <li><a href="{% url 'catalog:catalog' %}" class="nav-link px-2 text-{% if request.path == catalog %}white{% else %}secondary{% endif %}">Каталог</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'users:account' user.id %}" class="nav-link px-2 text-{% if request.path == users_account %}white{% else %}secondary{% endif %}">Личный кабинет</a></li>
            <li><a href="\logout" class="nav-link px-2 text-secondary">Выйти</a></li>
            {% endif %}
        </ul>
    </div>
</header>