VolunteerProject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('catalog/', include('catalog.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.urls import path
from . import views

app_name = 'catalog'

urlpatterns = [
    path('add', views.add_task, name='add_task'),
    path('', views.catalog, name='catalog'),
    path('task/<int:id>', views.catalog, name='task'),
]

store/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from . import views

app_name = 'store'

urlpatterns = [
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from . import views

app_name = 'users'

urlpatterns = [
    path('singup/volunteer', views.reg_volunteer, name='reg_vol'),
    path('singup/validator', views.reg_validator, name='reg_val'),
    path('singup/organization', views.reg_organization, name='reg_org'),
    path('login', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('account/<int:id>', views.personal_account, name='account'),
    path('account/<int:id>/edit', views.EditProfile, name='edit'),
]

users/models.py
from django.contrib.auth.models import User
from django.db import models
from store.models import Benefit


class AbstractFullUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    phone = models.CharField(max_length=16, blank=True)
    description = models.CharField(max_length=150, blank=True)
    photo = models.ImageField(upload_to='uploads', blank=True, verbose_name='Фотография')

    class Meta:
        abstract = True

    def __str__(self):
        return self.user.__str__()


class Volunteer(AbstractFullUser):
    points = models.IntegerField(default=0)
    benefits = models.ManyToManyField(Benefit, blank=True)


class Organization(AbstractFullUser):
    name = models.CharField(max_length=80, blank=True)
    address = models.CharField(max_length=150, blank=True)


class Validator(AbstractFullUser):
    pass

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class AbstractRegistrationForm(UserCreationForm):
    pass

    class Meta(UserCreationForm.Meta):
        model = User
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control', 'autocomplete': 'new-password'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control', 'autocomplete': 'new-password'}),
        }

        fields = ('username', 'email', 'first_name', 'last_name')


class VolunteerRegistrationForm(AbstractRegistrationForm):
    pass


class ValidatorRegistrationForm(AbstractRegistrationForm):
    pass


class OrganizationRegistrationForm(AbstractRegistrationForm):
    pass


class EditProfileForm(forms.Form):
    phone = forms.CharField()
    description = forms.CharField()
    photo = forms.ImageField()
    address = forms.CharField()
    name = forms.CharField()

users/views.py
import django.contrib.auth.models
from django.contrib.auth import login
from django.shortcuts import render, redirect

from catalog.models import Task
from store.models import Benefit
from .forms import VolunteerRegistrationForm, ValidatorRegistrationForm, OrganizationRegistrationForm
from .models import Volunteer, Validator, Organization, User


def reg_volunteer(request):
    form = VolunteerRegistrationForm()
    if request.method == 'POST':
        formed = VolunteerRegistrationForm(request.POST)
        if formed.is_valid():
            user = formed.save()
            volunteer = Volunteer(user=user,)
            volunteer.save()
            login(request, user)
            return redirect('/')
    return render(request, "users/register_volunteer.html", {"form": form})


def reg_validator(request):
    return redirect('/')
    # form = ValidatorRegistrationForm()
    # if request.method == 'POST':
    #     formed = ValidatorRegistrationForm(request.POST)
    #     if formed.is_valid():
    #         user = formed.save()
    #         validator = Validator(user=user)
    #         validator.save()
    #         login(request, user)
    #         return redirect('/')
    # return render(request, "users/register_validator.html", {"form": form})


def reg_organization(request):
    form = OrganizationRegistrationForm()
    if request.method == 'POST':
        formed = OrganizationRegistrationForm(request.POST)
        if formed.is_valid():
            user = formed.save()
            organization = Organization(user=user)
            organization.save()
            login(request, user)
            return redirect('/')
    return render(request, "users/register_organization.html", {"form": form})


def personal_account(request, id):
    user = User.objects.get(id=id)
    try:
        tasks = Task.objects.filter(organization=user.organization)
    except BaseException:
        tasks = []
    try:
        tasks_to_u = Task.objects.filter(users=user.volunteer)
        benefits = Benefit.objects.all()
        if request.method == "POST":
            if request.POST.get("buy"):
                benefit = Benefit.objects.get(id=int(request.POST.get("buy")))
                user.volunteer.points -= benefit.cost
                user.volunteer.benefits.add(benefit)
                user.volunteer.save()
            if request.POST.get("cancel"):
                task = Task.objects.get(id=int(request.POST.get("cancel")))
                task.users.remove(user.volunteer)
    except BaseException:
        benefits = []
        tasks_to_u = []
    return render(request, 'users/personal_account.html', {'account_user': user,
                                                           'tasks': tasks,
                                                           'tasks_to_u': tasks_to_u,
                                                           'benefits': benefits,
                                                           })


def EditProfile(request):
    return redirect('/')

templates/users/edit_profile.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<h3 class="text-white blockky" style="text-align:center;">Регистрация Организации</h3>
    <h5 class="text-white blockky" style="text-align:center;">От имени представителя</h5>
    <div class="card shadow border-nuke border-3 blockky" style="background: #C5C6C7;">
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                <div class="row g-3 align-items-center">

                    <p style="text-align:center;">{{ field.label }}</p>

                    {{ field }}
                    {% if field.errors %}
                        <p class="form-text" style="color: blue;">{{ field.errors }}</p>
                    {% endif %}
                </div>
                <hr>
                {% endfor %}
                <div class="d-grid">
                    <button type="submit" class="btn" style="background: #45A29E;">Отправить</button>
                </div>
            </form>
        </div>
    </div>{% endblock %}

templates/users/login.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<h3 class="text-white blockky" style="text-align:center;">Вход</h3>
<div class="card shadow border-nuke border-3 blockky" style="background: #C5C6C7;">
    <div class="card-body">
        <form method="POST" class="form-group">
            {% csrf_token %}
            <div class="mb-3">
                <label for="Username" class="form-label">Логин</label>
                <input class="form-control" name="username" id="id_username">
            </div>
            <div class="mb-3">
                <label for="Password" class="form-label">Пароль</label>
                <input type="password" class="form-control" name="password" id="id_password">
                <div id="passwordHelp" class="form-text">Нет аккаунта? Создайте <a
                        href="{% url 'users:reg_vol'%}">тут</a></div>
            </div>
            <div class="d-grid">
                <button type="submit" class="btn" style="background: #45A29E;">Войти</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/users/personal_account.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<div class="card shadow border-3 text-white" style="background: #27323f; border-color: #2f3c4c !important;">
    <div class="card-body" style="text-align:center;">
        <div class="row lg-2">
            <div class="col">
                {% if account_user.organization.photo %}
                <img src="{{account_user.organization.photo.url}}" width="100%" height="400">
                {% elif account_user.volunteer.photo %}
                <img src="{{account_user.volunteer.photo.url}}" width="100%" height="400">
                {% elif account_user.validator.photo %}
                <img src="{{account_user.validator.photo.url}}" width="100%" height="400">
                {% else %}
                <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="100%"
                     height="400"
                     xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500"
                     preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                    <rect width="100%" height="100%" fill="#eee"></rect>
                    <text x="40%" y="49%" fill="#aaa" dy=".3em">Фотография</text>
                </svg>
                {% endif %}
            </div>
            <div class="col" style="text-align:left;">
                <h5>Информация</h5>
                <hr>
                {% if account_user.organization %}
                <p> Ответственный: {{ account_user.first_name }} {{ account_user.last_name }}</p>
                <hr>
                <p>Название: {{ account_user.organization.name }}</p>
                <p>Номер телефона: {{ account_user.organization.phone }}</p>
                <p>Адрес: {{ account_user.organization.address }}</p>
                <p>Подробнее: {{ account_user.organization.description }}</p>
                {% elif account_user.validator %}
                <p> Ответственный: {{ account_user.first_name }} {{ account_user.last_name }}</p>
                <hr>
                <p>Номер телефона: {{ account_user.validator.phone }}</p>
                <p>Подробнее: {{ account_user.validator.description }}</p>
                {% elif account_user.volunteer %}
                <p> Волонтер: {{ account_user.first_name }} {{ account_user.last_name }} ( {{ account_user.username }} )</p>
                <hr>
                <p>Номер телефона: {{ account_user.volunteer.phone }}</p>
                <p>Подробнее: {{ account_user.volunteer.description }}</p>
                <p>Очки: {{ account_user.volunteer.points }}</p>
                {% endif %}
                {% if user.id == account_user.id %}
                <a href="" class="bnt bnt-warning">Изменить информацию</a>
                {% endif%}
            </div>
        </div>
    </div>
</div>
<div class="row py-2">
    <div class="col">
        <div class="card shadow border-3 blockky850 text-white"
             style="background: #27323f; border-color: #2f3c4c !important;">
            <div class="card-body" style="text-align:center;">
                {% if account_user.organization %}
                <h5>Ваши вакансии:</h5>
                <hr>
                <div class="row cols-2">
                    {% for task in tasks %}
                    <div class="col">
                        <div class="card shadow border-nuke border-1 blockky-null" style="background: #B5B6B7;">
                            <div class="card-body">
                                <p style="color: #000000;">{{ task.name }}</p>
                                <img class="rounded-3" src="{{ task.photo.url }}" width="100%" height="100%">
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% if user.id == account_user.id %}
                <a href="{% url 'catalog:add_task'%}" class="btn d-grid py-1" style="background: #45A29E;">Добавить
                    вакансию</a>
                {% endif %}
                {% elif account_user.validator %}
                <h5>Транзакции для проверки:</h5>
                <hr>
                {% for task in tasks %}
                <div class="card shadow border-nuke border-1 blockky-null" style="background: #B5B6B7;">
                    <div class="card-body">
                        <p style="color: #000000;">{{ task.name }}</p>
                        <img class="rounded-3" src="{{ task.photo.url }}" width="100%" height="100%">
                    </div>
                </div>
                {% endfor %}
                <a href="{% url 'catalog:add_task'%}" class="btn d-grid py-1" style="background: #45A29E;">Добавить
                    вакансию</a>
                {% elif account_user.volunteer %}
                <h5>Текущие задания:</h5>
                <hr>
                {% for task in tasks_to_u %}
                <div class="card shadow border-nuke border-1 blockky-null" style="background: #B5B6B7;">
                    <div class="card-body">
                        <p style="color: #000000;">{{ task.name }}</p>
                        <img class="rounded-3" src="{{ task.photo.url }}" width="100%" height="100%">
                        <form method="post" action="">
                            {% csrf_token %}
                            <div class="d-grid">
                                <button type="submit" name="cancel" value="{{ task.id }}" class="btn"
                                        style="background: #45A29E;">Отказаться
                                </button>
                            </div>
                        </form>
                    </div>
                </div>

                {% endfor %}
                {% endif %}
            </div>
        </div>
    </div>
    {% if account_user.volunteer and user.is_authenticated%}
    <div class="col py-2">
        <div class="card shadow border-3 blockky text-white"
             style="background: #27323f; border-color: #2f3c4c !important;">
            <div class="card-body" style="text-align:center;">
                <h5>Льготы:</h5>
                <hr>
                {% for benefit in benefits %}
                <div class="card shadow border-nuke border-1 blockky-null" style="background: #B5B6B7;">
                    <div class="card-body">
                        <p style="color: #000000;">Название: {{ benefit.name }}</p>
                        <p style="color: #000000;">Описание: {{ benefit.description }}</p>
                        <p style="color: #000000;">Стоимость: {{ benefit.cost }}</p>
                        {% if benefit not in account_user.volunteer.benefits.all%}
                        <form method="post" action="">
                            {% csrf_token %}
                            <div class="d-grid">
                                <button type="submit" name="buy" value="{{ benefit.id }}" class="btn"
                                        style="background: #45A29E;">Купить
                                </button>
                            </div>
                        </form>
                        {% else %}
                        <div class="d-grid">
                            <button type="submit" name="buy" value="{{ task.id }}" class="btn bnt-warning"
                                    style="background: #f5e042;">Куплено
                            </button>
                        </div>
                        {% endif%}
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

templates/users/register_organization.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">

    <link rel="apple-touch-icon" sizes="180x180" href="/static/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/static/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/static/favicon/favicon-16x16.png">
    <link rel="manifest" href="/static/favicon/site.webmanifest">
    <link rel="mask-icon" href="/static/favicon/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Title</title>
    <style>
        .blockky {
            display: block;
            margin-left: auto;
            margin-right: auto;
            margin-top: 20px;
            height: 100%;
            width: 650px;
            padding: 10px;
        }

        .border-nuke {
            border-color: #45A29E !important;
        }

    </style>
</head>
<body style="background: #1F2833;">
<main>
    <h3 class="text-white blockky" style="text-align:center;">Регистрация Организации</h3>
    <h5 class="text-white blockky" style="text-align:center;">От имени представителя</h5>
    <div class="card shadow border-nuke border-3 blockky" style="background: #C5C6C7;">
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                <div class="row g-3 align-items-center">

                    <p style="text-align:center;">{{ field.label }}</p>

                    {{ field }}
                    <span id="passwordHelpInline" class="form-text">
                        {{ field.help_text }}
                    </span>
                    {% if field.errors %}
                        <p class="form-text" style="color: blue;">{{ field.errors }}</p>
                    {% endif %}
                </div>
                <hr>
                {% endfor %}
                <div class="d-grid">
                    <button type="submit" class="btn" style="background: #45A29E;">Отправить</button>
                </div>
            </form>
        </div>
    </div>

    <div class="card shadow border-3 blockky text-white" style="background: #27323f; border-color: #2f3c4c !important;">
        <div class="card-body" style="text-align:center;">
            <p>Вы волонтёр?</p>
            <p>Можете зарегистрироваться <a href="{% url 'users:reg_vol' %}">тут</a></p>
            <hr>
            <p>Вы проверяющий какой-либо организации?</p>
            <p>Можете зарегистрироваться как проверяющий <a href="{% url 'users:reg_val' %}">тут</a></p>
        </div>
    </div>
</main>
{% include "includes/footer.html" %}
{% include "includes/endscripts.html" %}
</body>
</html>

templates/users/register_validator.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">

    <link rel="apple-touch-icon" sizes="180x180" href="/static/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/static/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/static/favicon/favicon-16x16.png">
    <link rel="manifest" href="/static/favicon/site.webmanifest">
    <link rel="mask-icon" href="/static/favicon/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Title</title>
    <style>
        .blockky {
            display: block;
            margin-left: auto;
            margin-right: auto;
            margin-top: 20px;
            height: 100%;
            width: 650px;
            padding: 10px;
        }

        .border-nuke {
            border-color: #45A29E !important;
        }

    </style>
</head>
<body style="background: #1F2833;">
<main>
    <h3 class="text-white blockky" style="text-align:center;">Регистрация Проверяющего</h3>
    <div class="card shadow border-nuke border-3 blockky" style="background: #C5C6C7;">
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                <div class="row g-3 align-items-center">
                    <p style="text-align:center;">{{ field.label }}</p>
                    {{ field }}
                    <span id="passwordHelpInline" class="form-text">
                        {{ field.help_text }}
                    </span>
                    {% if field.errors %}
                        <p class="form-text" style="color: blue;">{{ field.errors }}</p>
                    {% endif %}
                </div>
                <hr>
                {% endfor %}
                <div class="d-grid">
                    <button type="submit" class="btn" style="background: #45A29E;">Отправить</button>
                </div>
            </form>
        </div>
    </div>

    <div class="card shadow border-3 blockky text-white" style="background: #27323f; border-color: #2f3c4c !important;">
        <div class="card-body" style="text-align:center;">

            <p>Вы представитель организации?</p>
            <p>Можете зарегистрировать свою организацию <a href="{% url 'users:reg_org' %}">тут</a></p>
            <hr>
            <p>Вы волонтёр?</p>
            <p>Можете зарегистрироваться <a href="{% url 'users:reg_vol' %}">тут</a></p>
        </div>
    </div>
</main>
{% include "includes/footer.html" %}
{% include "includes/endscripts.html" %}
</body>
</html>

templates/users/register_volunteer.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">

    <link rel="apple-touch-icon" sizes="180x180" href="/static/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/static/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/static/favicon/favicon-16x16.png">
    <link rel="manifest" href="/static/favicon/site.webmanifest">
    <link rel="mask-icon" href="/static/favicon/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Title</title>
    <style>
        .blockky {
            display: block;
            margin-left: auto;
            margin-right: auto;
            margin-top: 20px;
            height: 100%;
            width: 650px;
            padding: 10px;
        }

        .border-nuke {
            border-color: #45A29E !important;
        }

    </style>
</head>
<body style="background: #1F2833;">
<main>
    <h3 class="text-white blockky" style="text-align:center;">Регистрация Волонтера</h3>
    <div class="card shadow border-nuke border-3 blockky" style="background: #C5C6C7;">
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                <div class="row g-3 align-items-center">

                    <p style="text-align:center;">{{ field.label }}</p>

                    {{ field }}
                    <span id="passwordHelpInline" class="form-text">
                        {{ field.help_text }}
                    </span>
                    {% if field.errors %}
                        <p class="form-text" style="color: blue;">{{ field.errors }}</p>
                    {% endif %}
                </div>
                <hr>
                {% endfor %}
                <div class="d-grid">
                    <button type="submit" class="btn" style="background: #45A29E;">Отправить</button>
                </div>
            </form>
        </div>
    </div>

    <div class="card shadow border-3 blockky text-white" style="background: #27323f; border-color: #2f3c4c !important;">
        <div class="card-body" style="text-align:center;">

            <p>Вы представитель организации?</p>
            <p>Можете зарегистрировать свою организацию <a href="{% url 'users:reg_org' %}">тут</a></p>
            <hr>
            <p>Вы проверяющий какой-либо организации?</p>
            <p>Можете зарегистрироваться как проверяющий <a href="{% url 'users:reg_val' %}">тут</a></p>
        </div>
    </div>
</main>
{% include "includes/footer.html" %}
{% include "includes/endscripts.html" %}
</body>
</html>